### ISSUE TITLE
Example is failing

### ISSUE THREAD

**Issue by justinwhite** [andyyao95/walkr#1]
Running the example in the README fails:

```
> library(walkr)
> A <- matrix(1, ncol = 3)
> b <- 1
> sampled_points <- walkr(A = A, b = b, points = 1000, method = "dikin")
> explore_walkr(sampled_points)
Error: is.list(x) is not TRUE
```

Believe the assertion in https://github.com/andyyao95/walkr/blob/master/R/explore_walkr.R#L21 is the one breaking. This is using version `walkr_0.3-2`.

**Comment by andyyao95** [comment]
Hi Justin,

Sorry about this. I should've updated the example. The default return format for walkr is a matrix of points. In order to use `explore_walkr()`, you need to specify `ret.format = "list"`. 

`
sampled_points <- walkr(A = A, b = b, points = 1000, method = "dikin", ret.format = "list")
explore_walkr(sampled_points)
`

That should work. Thanks for the note. I'll fix the README right now.
